


POST http://localhost:8080/api/auth/connect 


### Listar Chaves PIX de conta principal
GET http://localhost:8080/api/pix/mock/receive

### Listar Chaves PIX de mock
GET http://localhost:8080/api/pix/mock/payment



### Listar Dispositivos
GET http://localhost:8080/api/pix/device/list



### Gerar Copia e cola
POST http://localhost:8080/api/pix/payment-string
Content-Type: application/json

{
    "documentoId": "contratoAF",
    "valor": 10.00,
    "reutilizavel":false,
    "calendarioExpiracaoSegundos": 3456000
}