


POST http://localhost:8080/api/auth/connect 


###

GET http://localhost:8080/api/accounts


###
GET http://localhost:8080/api/accounts/0520386164/balance


###
GET http://localhost:8080/api/accounts/0520386164/history